### ISSUE TITLE
Please add a FLOSS license

### ISSUE THREAD

**Issue by DrMcCoy** [leafo/itchio-app-old#31]
Right now, itchio-app has no license at all, [which generally means that default copyright laws apply and people can't do anything with the code](http://choosealicense.com/no-license/). This is probably not what you want.

Please consider [choosing an appropriate free software license](http://choosealicense.com/) and denoting the license in the source tree by:
- Adding a LICENSE / COPYING text file to the project's root
- Mentioning the license by name in the README.md
- Ideally adding copyright / license information header comments to each source file

Thanks.

**Comment by leafo** [comment]
Thanks for heads-up, license added.

**Comment by DrMcCoy** [comment]
Thanks! :)
